dist: bionic

language: minimal

services:
  - docker

sudo: required

before_install:
  - sudo apt-get install --no-install-recommends --yes build-essential python3 python3-pip python3-setuptools
  - pip3 install --upgrade --user setuptools
  - pip3 install --upgrade --user wheel

install:
  - pip3 install --user ansible docker==3.7.3 molecule requests==2.20.1

jobs:
  include:
    before_script:
      - mkdir --parents ./artifacts/installer
      - sudo docker pull talsenteam/docker-ci-image-dotnet-core-runtime:v2.1
      - sudo docker pull talsenteam/docker-ci-image-dotnet-core-sdk:v2.1
      - sudo docker pull ubuntu:bionic
    script:
      - /bin/bash bash-ci/run-pipeline.sh
