dist: bionic

language: minimal

services:
  - docker

sudo: required

jobs:
  include:
    stage: 'build-and-test'
    name: 'build-and-test-dotnet-application'
    image: 'talsenteam/docker-ci-image-dotnet-core-sdk:v2.1'
    script:
      - /bin/bash bash-gitlab-ci/run-dotnet-tests.sh
      - /bin/bash bash-gitlab-ci/run-dotnet-build.sh
