dist: bionic

language: minimal

services:
  - docker

sudo: required

jobs:
  include:
    before_script:
      - sudo docker pull talsenteam/docker-ci-image-dotnet-core-sdk:v2.1
    script:
      - echo "Build and test dotnet application ..."
      - sudo docker run --detach --rm --name=stage-1-build-and-test --workdir=/APPIOframework talsenteam/docker-ci-image-dotnet-core-sdk:v2.1 sleep infinity
      - sudo docker cp --archive . stage-1-build-and-test:/APPIOframework
      - sudo docker exec stage-1-build-and-test ls -Al .
      - sudo docker exec stage-1-build-and-test /bin/bash bash-gitlab-ci/run-dotnet-tests.sh
      - sudo docker exec stage-1-build-and-test /bin/bash bash-gitlab-ci/run-dotnet-build.sh
      - sudo docker stop stage-1-build-and-test
      - echo "Build and test dotnet application ... done"
    after_script:
      - sudo docker rmi talsenteam/docker-ci-image-dotnet-core-sdk:v2.1
