---
galaxy_info:
  author: talsen team GmbH
  description: Tests the 'appio help' command.
  company: talsen team GmbH
  license: MPL-2.0
  min_ansible_version: 2.4
  platforms:
    - name: ubuntu
      versions:
        - disco
  galaxy_tags: []
dependencies: []
