---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: test-appio-clean--help
    image: talsenteam/docker-ci-image-dotnet-core-runtime:v2.1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: build--help
  test_sequence:
    - lint
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
